### ISSUE TITLE
Youtube integration

### ISSUE THREAD

**Issue by clarriu97** [clarriu97/social-sync#2]
## Context

Integration with Youtube is wanted to upload content directly to this platform.

## Goal

- Create tools and scripts to update content in all situations.

## Tasks

- [x] Architect the options for the videos: shorts or normal, format, tittle, subtitle, tags, thumbnail, etc.
- [x] Create the data structures with pydantic.
- [x] Code the solution with a cli application.

## References

- [Youtube API py thon Quickstart](https://developers.google.com/youtube/v3/quickstart/python?hl=es-419)
- [Upload videos to youtube with python](https://developers.google.com/youtube/v3/guides/uploading_a_video?hl=es-419)
