### ISSUE TITLE
Twitter implementation

### ISSUE THREAD

**Issue by clarriu97** [clarriu97/social-sync#3]
## Context

Integration with Twitter is wanted to upload content directly to this platform.

## Goal

- Create tools and scripts to update content in all situations.

## Tasks

- [x] Architect the options for the videos: shorts or normal, format, tittle, subtitle, tags, thumbnail, etc.
- [x] Create the data structures with pydantic.
- [x] Code the solution with a cli application.

## References

- [Tweepy](https://docs.tweepy.org/en/latest/)
