### ISSUE TITLE
Tiktok implementation

### ISSUE THREAD

**Issue by clarriu97** [clarriu97/social-sync#4]
## Context

Integration with Tiktok is wanted to upload content directly to this platform.

## Goal

- Create tools and scripts to update content in all situations.

## Tasks

- [ ] Architect the options for the videos: shorts or normal, format, tittle, subtitle, tags, thumbnail, etc.
- [ ] Create the data structures with pydantic.
- [ ] Code the solution with a cli application.

## References

- [TiktokApi](https://github.com/davidteather/TikTok-Api)
